#!/usr/bin/env bash
# Bash script to configure a server nginx to listen on port 80
sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart