#!/usr/bin/env bash
# Bash script to configure nginx server to listen on port 80 (sweet)
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo rm /var/run/nginx.pid
