#!/usr/bin/env bash
# display Best School 10 times

COUNTER=0
while [ $COUNTER -le 10 ]
do
if [ $COUNTER -eq 4 ]
then
echo "bad luck"
elif [ $COUNTER -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
COUNTER=$((COUNTER+1))
done
